In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"diamonds.csv", sep=",")

In [2]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [7]:
df['carat'] == '0.23'

0        False
1        False
2        False
3        False
4        False
         ...
53935    False
53936    False
53937    False
53938    False
53939    False
Name: carat, Length: 53940, dtype: bool

In [9]:
df[ df['carat'] >  0.23 ]

       carat        cut color clarity  depth  table  price     x     y     z
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53621 rows x 10 columns]

In [10]:
df.query('carat > 0.70')

       carat        cut color clarity  depth  table  price     x     y     z
91      0.86       Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
93      0.71  Very Good     E     VS2   62.4   57.0   2759  5.68  5.73  3.56
94      0.78  Very Good     G     SI2   63.8   56.0   2759  5.81  5.85  3.72
97      0.96       Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
98      0.73  Very Good     E     SI1   61.6   59.0   2760  5.77  5.78  3.56
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[26778 rows x 10 columns]

In [11]:
# user variable

In [14]:
vMinDepth = 65.0
df.query('depth >@vMinDepth')

       carat   cut color clarity  depth  table  price     x     y     z
8       0.22  Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
42      0.26  Good     D     VS2   65.2   56.0    403  3.99  4.02  2.61
97      0.96  Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
124     0.70  Fair     F     VS2   65.3   55.0   2762  5.63  5.58  3.66
129     0.91  Fair     H     SI2   65.7   60.0   2763  6.03  5.99  3.95
...      ...   ...   ...     ...    ...    ...    ...   ...   ...   ...
53727   0.78  Fair     E     SI2   66.9   57.0   2721  5.70  5.66  3.60
53800   0.90  Fair     I     VS1   68.7   62.0   2732  5.83  5.79  3.99
53863   1.00  Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04  Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53882   0.71  Fair     D     VS1   65.4   59.0   2747  5.62  5.58  3.66

[835 rows x 10 columns]